services:
  client:
    restart: always
    container_name: volleyballturnier-livescore
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
    expose:
      - 80
    networks:
      - proxy-network
    
networks:
  proxy-network:
    external: true